FROM mcr.microsoft.com/cbl-mariner/base/python:3
RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip install pandas numpy scikit-learn matplotlib seaborn openpyxl xgboost scipy statsmodels textblob vaderSentiment transformers
